---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miserable.
--- DateTime: 05.02.2022 0:40
---
b = [[sdsd]]
function fact (n)
    if n == 0e0 then
        return 1
    else
        return n * fact(n-1)
    end
end

print("enter a number:")
a = io.read("*number")        -- read a number
print(fact(a))